### ISSUE TITLE
An idea for tactical response

### ISSUE THREAD

**Issue by gorsuch** [jagthedrummer/canary-ember#1]
Hi!  As we had [discussed on the twitters](https://twitter.com/jagthedrummer/status/465579069258493952), I'm dropping an issue to provide some ideas on how I used your dashboard in an incident and how I think it might be made better for that use case.

First off, this is just my subjective view.  Second, don't build for me - build to solve your own problems.  If my point of view helps, awesome.  If not, don't feel like you need to take my advice for a single second.  I won't be offended.

So last night, I was writing up a GitHub issue when I started getting 503's.  Whoa.  This was before my pager went off, so the first thing I did was jump on your dashboard to see what canary.io was seeing.  The default view, which emphasizes response time, wasn't particularly revealing, as the site was responding with 503s with plenty of speed.  It was immediately useful, however, as soon as I drilled down into the `do-ny2` location and was able to gauge the various response codes via that wheel on the lower right.

When responding to an incident, I think I'm looking for two charts on the main page: one that shows me latency and ones that helps me understand error rates across the timeline.  I would then ideally be able to drill into the one that seems relevant, which might then show me a graph per location.

In either case, when performing remediation, I'm keeping an eye on the right hand side of the chart, allowing me to know if my actions are helping or not.  That's one giant benefit to multiple measurements per second - faster feedback loops.

So yeah, that's my perspective.  I'm not sure what you are aiming for, so again, please don't think you have to build custom tooling just to suit my desires.  However, I would say, that I imagine that's a common need for this crowd.

:v: and :heart:.  Let me know if you have any questions!

**Comment by jagthedrummer** [comment]
With the main canary project being in transition and the JSON endpoint no longer running I'm just going to close this. Thanks to everyone who pitched in on this project!
