### ISSUE TITLE
Blacklist some locations?

### ISSUE THREAD

**Issue by gorsuch** [jagthedrummer/canary-ember#2]
Hey @jagthedrummer.  `do-sf1` is a very annoying location right now, but I don't want to remove it from canary proper.  Being able to showcase regions and providers that are flaky is actually something I'm quite interested in.

I was thinking of standing up a url / json file that would contain an array of locations that are currently considered problematic within the system.  Secondary services such as your dashboard would be able to poll for that list of locations and take appropriate action, such as discarding those sites from the view.

Would that be useful to you?  Does it make sense?

**Comment by jagthedrummer** [comment]
With the main canary project being in transition and the JSON endpoint no longer running I'm just going to close this. Thanks to everyone who pitched in on this project!
