### ISSUE TITLE
Handle non-zero exit status

### ISSUE THREAD

**Issue by ryoe** [jagthedrummer/canary-ember#3]
When a non-zero `exit_status` is returned, the following are all undefined:
- `http_status`
- `local_ip`
- `primary_ip`
- `namelookup_time`
- `connect_time`
- `starttransfer_time`
- `total_time`

When these data are included, we see graphs like this:
![screen shot 2014-05-23 at 7 19 42 pm](https://cloud.githubusercontent.com/assets/1404427/3073146/ac237e1e-e2da-11e3-9c04-ed13bb5714aa.png)

Here's a snippet of JSON data that illustrates the issue:

```
[
  {
    "check": {
      "id": "http-github.com",
      "url": "http://github.com"
    },
    "id": "55f87c18-a4ea-4898-7d0a-72f521fe84ed",
    "location": "rax-hkg",
    "t": 1400890202,
    "exit_status": 0,
    "http_status": 301,
    "local_ip": "119.9.75.14",
    "primary_ip": "192.30.252.129",
    "namelookup_time": 0.001658,
    "connect_time": 0.220197,
    "starttransfer_time": 0.438365,
    "total_time": 0.438381
  },
  {
    "check": {
      "id": "http-github.com",
      "url": "http://github.com"
    },
    "id": "263ba0c7-d8ae-41d3-6eae-dda5ba1611a2",
    "location": "rax-ord",
    "t": 1400890202,
    "exit_status": 28
  },
  {
    "check": {
      "id": "http-github.com",
      "url": "http://github.com"
    },
    "id": "22ab4d71-d983-4e2a-4ad7-6afd15c88e67",
    "location": "rax-dfw",
    "t": 1400890202,
    "exit_status": 0,
    "http_status": 301,
    "local_ip": "23.253.225.112",
    "primary_ip": "192.30.252.130",
    "namelookup_time": 0.00246,
    "connect_time": 0.039897,
    "starttransfer_time": 0.077351,
    "total_time": 0.077374
  }
]
```

Hopefully, it will be relatively easy to avoid including "undefined" data in the graphs.

**Comment by jagthedrummer** [comment]
With the main canary project being in transition and the JSON endpoint no longer running I'm just going to close this. Thanks to everyone who pitched in on this!
