### ISSUE TITLE
Make API and URLs configurable

### ISSUE THREAD

**Issue by blalor** [jagthedrummer/canary-ember#7]
It'd be great if I could just specify the base URL for the Canary API and the location of the JSON file containing check definitions in a config file.  Right now I have to hack application.js and measurements.js (?) when I want to use a private instance of Canary.

**Comment by jagthedrummer** [comment]
With the main canary project being in transition and the JSON endpoint no longer running I'm just going to close this. Thanks to everyone who pitched in on this project!

**Comment by gorsuch** [comment]
<3
